### ISSUE TITLE
Sorting an array of entries according to a fixed list/array of items - not working?

### ISSUE THREAD

**Issue by TUSAB-web** [TopShelfCraft/SuperSort#12]
I found this on stack exchange; it’s 5 years old, so maybe this doesn’t work anymore?

https://craftcms.stackexchange.com/questions/11050/sorting-an-array-of-entries-according-to-a-fixed-list-array-of-items

The suggested way on that page is:

```
{% set foo = craft.entries.section('foo')... %}

{% set sortAsList = {
    'ShopType1': "A",
    'ShopType2': "B",
    'ShopType3': "C"
} %}

{% set sortedFoo = foo | supersort('sortAs', '{ shopType | replace(sortAsList) }') %}
```

I put this into my code and it doesn’t seem to work...

**Comment by michaelrog** [comment]
That strategy _should_ work still fine. (If it doesn't, double-check your template code to make sure variables have the values you think they do.)

FWIW — I added some [custom-list and custom-function sorting methods](https://github.com/TopShelfCraft/SuperSort/commit/18417a0780fd3527b9965b3dd967f4c08bd46757) in the latest release (3.1.0). Haven't merged those to `master` yet, since they aren't documented, but you can still play around with them if you want (if you're updated to the latest release).
