### ISSUE TITLE
"Array to string conversion" notice when calling SuperSort on an ElementQuery

### ISSUE THREAD

**Issue by parktool** [TopShelfCraft/SuperSort#2]
I'm trying to use SuperSort to natural sort product entries by their Product Number, using this code: 

`{% set categoryProducts = craft.entries.section('product').relatedTo(category) %}`
`{% set categoryProducts = categoryProducts|supersort('natsortAs', '{productNumber}') %}`

When I do this, I get a PHP error "Array to string conversion." Does SuperSort not work on entry models, or is there something I'm not doing that I should be?

**Comment by michaelrog** [comment]
SuperSort should work with `EntryModel` objects just fine.

What kind of field is `productNumber`?

Could you enable Dev Mode and post the stack trace that shows what actual values are being passed in that are causing the error?

**Comment by parktool** [comment]
productNumber is a plain text field.

I attached the stack trace as an htm file.
[PHP_notice.htm.zip](https://github.com/TopShelfCraft/SuperSort/files/759019/PHP_notice.htm.zip)

**Comment by michaelrog** [comment]
From your error message, it looks like SuperSort is treating `categoryProducts` as an object, rather than an array. This makes sense, because `craft.entries` returns an EntryQuery, and implicitly iterating over element queries is not longer supported in Craft 3.

Perhaps, ideally, SuperSort could take care of implicitly casting the query to a set of results... but then again, it's not bad to be consistent with Craft's own conventions... 🤔 

For now, add a `.all()` to query the results and return an array of elements, and then SuperSort will be able to process the _sort-as_ operation on your array.

i.e.:
```php
{% set categoryProducts = craft.entries.section('product').relatedTo(category).all() %}
```
